#!/usr/bin/env bash

# Homebrew
which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew bundle

defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

# Dock items
bash dock.sh

# Git
git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/" 

# Shell
rm -rf ~/.oh-my-zsh
echo "exit" | sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

rm -rf ~/.bash_profile ~/.zshrc

ln -s $(pwd)/bash_profile ~/.bash_profile
ln -s $(pwd)/zshrc ~/.zshrc

# Syntax highlighting for zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Theme for zsh
mkdir ~/.oh-my-zsh/themes
ln -s $(pwd)/timrcoulson.zsh-theme ~/.oh-my-zsh/themes/timrcoulson.zsh-theme

# Get 1pw and chrome to play nicely
xattr -r -d com.apple.quarantine /Applications/Google\ Chrome.app
xattr -r -d com.apple.quarantine /Applications/1Password\ 7.app

# Gopath
mkdir ~/go
