#!/usr/bin/env bash

# Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Gcloud
curl https://sdk.cloud.google.com > gcloud
exec -l $SHELL
gcloud init

defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

# Install dock items
bash dock.sh

cp bash_profile ~/.bash_profile

mv zshrc ~/.zshrc

git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/" 
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Syntax highlighting for zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

cp timcoulson.zsh-theme ~/.oh-my-zsh/themes/
